# whitelist
#branches:
#  only:
#    - master

os:
  - linux
  - osx

language: cpp
compiler:
  - gcc
  - clang
# Change this to your needs
script: pushd metabuilder/scripts/ci && ./ci_travis.sh && popd
