# Notes:
#---------------------------------#
# general configuration #
#---------------------------------#
 
# version format
version: 1.0.{build} # You can use {branch} to, for example
 
# you can use {branch} name in version format too
# version: 1.0.{build}-{branch}
 
# branches to build
branches:
# whitelist
#only:
#- master
#- production
 
# blacklist
except:
- gh-pages
   
#---------------------------------#
# environment configuration #
#---------------------------------#
 
# Operating system (build VM template)
os: Windows Server 2012
 
# scripts that are called at very beginning, before repo cloning
init:
- git config --global core.autocrlf input
 
# clone directory
clone_folder: c:\projects\myproject
 
# fetch repository as zip archive
shallow_clone: true # default is "false"
 
# set clone depth
clone_depth: 5 # clone entire repository history if not defined
 
# setting up etc\hosts file
hosts:
queue-server: 127.0.0.1
db.server.com: 127.0.0.2
 
# environment variables
environment:
my_var1: value1
my_var2: value2
 
# environment:
# global:
# connection_string: server=12;password=13;
# service_url: https://127.0.0.1:8090
#
# matrix:
# - db: mysql
# provider: mysql
#
# - db: mssql
# provider: mssql
# password:
# secure: $#(JFDA)jQ@#$
 
# this is how to allow failing jobs in the matrix
matrix:
fast_finish: true # set this flag to immediately finish build once one of the jobs fails.

#allow_failures:
#- platform: x86
#configuration: Debug
#- platform: x64
#configuration: Release
 
# scripts that run after cloning repository
install:
# by default, all script lines are interpreted as batch
- echo This is batch
# to run script as a PowerShell command prepend it with ps:
- ps: Write-Host 'This is PowerShell'
# batch commands start from cmd:
- cmd: echo This is batch again
- cmd: set MY_VAR=12345
  
#---------------------------------#
# build configuration #
#---------------------------------#
 
# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: Any CPU
 
# to add several platforms to build matrix:
#platform:
# - x86
# - Any CPU
 
# build Configuration, i.e. Debug, Release, etc.
configuration: Release
 
# to add several configurations to build matrix:
#configuration:
# - Debug
# - Release
 
build:
#parallel: true # enable MSBuild parallel builds
#project: MyTestAzureCS.sln # path to Visual Studio solution or project
 
# MSBuild verbosity level
verbosity: quiet|minimal|normal|detailed
 
# scripts to run before build
before_build:
 
# scripts to run after build
after_build:
 
# to run your custom scripts instead of automatic MSBuild
build_script:
metabuilder\metabuilder\scripts\buildall_windows.bat
 
# to disable automatic builds
#build: off

test: off
  
#---------------------------------#
# global handlers #
#---------------------------------#
 
# on successful build
on_success:
- do something
 
# on build failure
on_failure:
- do something
 
# after build failure or success
on_finish:
- do something
 
#---------------------------------#
# notifications #
#---------------------------------#
notifications:
 
# Email
- provider: Email
to:
- kjmac123@gmail.com
subject: 'Build {{status}}' # optional
message: "{{message}}, {{commitId}}, ..." # optional
on_build_status_changed: true
